Solving context error for the state. Getting unexpected error.
TypeError: Cannot read property 'length' of undefined
Looks like it can't read the length property if the state hasn't been set first. In theory we are adding a default value when we say images: [] but looks like it's not the correct way. In the tutorial seems to work anyways.